apiVersion: v1
kind: Pod
metadata: 
  name: multicontainer
  labels:
    project: roboshop
    environment: dev
spec:
  containers:
    - name: nginx_1
      image: nginx
    - name: nginx_2
      image: nginx