apiVersion: v1
kind: Pod
metadata: 
  name: multicontainer
  labels:
    project: roboshop
    environment: dev
spec:
  containers:
    - name: nginx-1
      image: nginx
    - name: nginx-2
      image: nginx