apiVersion: v1
kind: Pod
metadata:
  name: labels
  labels:
    project: roboshop
    tier: frontend
    environment: dev
spec:
  containers:
    - name: nginx_container
      image: nginx
     

    