apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    project: roboshop
    environment: dev
    tier: frontend
  annotations:
    description: "pod used for jenkins"
    jenkins: "https://jenkins.com/build/job/roboshop-catalouge/3"
spec:
  containers:
    - name:  nginx
      image: nginx
    