apiVersion: v1
kind: Pod
metadata:
  name: env-pod
  labels:
    project:  roboshop
    env: deb
    tier: frontend
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: course
          value: "devSecops"
        - name : "upskilling"
          value: "for bright future"