apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    project: roboshop
    tier: frontend
    environment: dev
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - secretRef:
            name: secret-pod