apiVersion: v1
kind: Service
metadata:
  name: nginx-service-lb
  labels:
    purpose: service-demo
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    environment: dev
    purpose: service-demo-lb
  ports:
    - protocol: TCP
      port: 80 ##serviceport
      targetPort: 80 ##targetport
---
apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  labels:
    project: roboshop
    environment: dev
    purpose: service-demo-lb
spec:
  containers:
    - name: nginx
      image: nginx